
# If set to true players won't receive any messages.
# For example: "YOU GOT SLAPPED!"
silentTroll: false

# Here you can edit the commands
commands:
  slap:
    name: "slap"
    description: "Slap someone!"
    permission: "llamatroll.slap"
  forcedrop:
    name: "forcedrop"
    description: "Force a player to drop his current item"
    permission: "llamatroll.forcedrop"
  dropall:
    name: "dropall"
    description: "Force a player to drop all his items."
    permission: "llamatroll.dropall"
  spin:
    name: "spin"
    description: "Spin a player."
    permission: "llamatroll.spin"
  silenttroll:
    name: "silenttroll"
    description: "Turn on/off Silenttroll."
    permission: "llamatroll.silenttroll"
  drunken:
    name: "drunken"
    description: "Make someone drunk."
    permission: "llamatroll.drunken"
  ignite:
    name: "ignite"
    description: "Set a player on fire."
    permission: "llamatroll.ignite"
  freeze:
    name: "freeze"
    description: "Freeze a player."
    permission: "llamatroll.freeze"
  unfreeze:
    name: "unfreeze"
    description: "Unfreeze a player."
    permission: "llamatroll.unfreeze"
  rocket:
    name: "rocket"
    description: "Launch a player."
    permission: "llamatroll.rocket"